variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Define a localização do cache da tarefa de análise
  GIT_DEPTH: "0"  # Informa ao git para buscar todos os branches do projeto, necessário para a tarefa de análise

stages:
  - test

sonarcloud-check:
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main" || $CI_PIPELINE_SOURCE == "merge_request_event"'
