variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "1"  # Reduzido para clonar apenas o último commit e a branch de destino
  SONAR_HOST_URL: "https://sonarcloud.io"
  SONAR_TOKEN: "9dffff8721e2658aeca8b14267d4f54963d93ade"

stages:
  - test

sonarcloud-check:
  stage: test
  image: maven:3-openjdk-17
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - mvn verify sonar:sonar -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN -Dsonar.projectKey=agendaapp2_AgendaApp
  only:
    - merge_requests
    - master
    - develop
    - main
    - dev
