variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Define o local do cache da tarefa de análise
  GIT_DEPTH: "0"  # Indica ao git para buscar todos os branches do projeto, necessário para a tarefa de análise
  SONAR_HOST_URL: "https://sonarcloud.io"  # URL do SonarCloud
  # Substitua 'seu_token_aqui' pelo seu token de acesso ao SonarCloud
  SONAR_TOKEN: "9dffff8721e2658aeca8b14267d4f54963d93ade"  # Token de acesso ao SonarCloud

stages:
  - test

sonarcloud-check:
  stage: test
  image: maven:3-openjdk-17
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - mvn verify sonar:sonar -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN -Dsonar.projectKey=agendaapp2_AgendaApp
  only:
    - merge_requests
    - master
    - develop
