variables:
  SONAR_TOKEN: "9dffff8721e2658aeca8b14267d4f54963d93ade"  # Substitua pelo seu token de acesso do SonarCloud
  SONAR_HOST_URL: "https://sonarcloud.io"  # URL do SonarCloud, se estiver usando SonarQube substitua pela URL do seu servidor

stages:
  - build
  - test
  - analyze  # Etapa para análise estática com SonarCloud

build:
  stage: build
  script:
    - echo "Fazendo o build aqui"

test:
  stage: test
  script:
    - echo "Rodando testes aqui"

sonarcloud-check:
  stage: analyze
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner \
        -Dsonar.host.url=$SONAR_HOST_URL \
        -Dsonar.projectKey=agendaapp2 \
        -Dsonar.organization=AgendaApp \
        -Dsonar.login=$SONAR_TOKEN